[package]
name = "rusty-can-opener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open-dict = { version = "0.1.0", path = "open-dict" }
[workspace]
members = ["open-dict"]
